<?xml version="1.0"  encoding="UTF-8"?>
<!DOCTYPE auto[
<!ELEMENT auto (modelo, marca, color, placas)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT placas (#PCDATA)>
]>

<auto>
    <modelo>Tsuru</modelo>
    <marca>Nissan</marca>
    <color>Blanco</color>
    <placas>7D48S4</placas>
</auto>